### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by DanielOaks** [bibanon/world4ch#2]
We should have a search feature that lets you search OPs, threads, posts, etc. Possibly look at the typical FoolFuuka search box for inspiration?

**Comment by antonizoon** [comment]
Probably want to try using Sphinx just like FoolFuuka does. It's powerful and works in Python.

**Comment by antonizoon** [comment]
I guess search is accomplished by https://archive.tinychan.org already, along with a full functioning archive.
